---

- name: Ensure nginx packages are installed
  apt: name="{{ item }}" state=present
  tags: [nginx, packages]
  with_items: "{{ nginx_packages }}"

#- include: install_from_source.yml
#  when: "{{ nginx_install_source }}" == "true" and ansible_service_mgr != "systemd"
#  tags: [nginx, source]

- include: install_from_source_systemd.yml
  when: "{{ nginx_install_source }}" # and ansible_service_mgr == "systemd"
  tags: [nginx, source]

- name: Ensure nginx configuration file is correct
  template: src=templates/nginx.conf.j2 dest="{{ nginx_conf_dir }}/nginx.conf" owner=root group=root mode=0644
  tags: [nginx, config]
  
- name: Ensure nginx is started and enabled
  service: name=nginx state=started enabled=yes
  tags: [nginx]
